runtime: nodejs20

instance_class: F2

env_variables:
  NODE_ENV: "production"

handlers:
  # Serve static files from the dist directory
  - url: /assets
    static_dir: dist/assets
    secure: always

  # Serve the main HTML file
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

  # Route all API requests to the backend
  - url: /api/.*
    script: auto
    secure: always

  # Fallback to index.html for client-side routing
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
